Logging:
  default: INFO

General:
    Modus:         Collider
    Time_Step_Mode: Fixed
    Delta_Time:    0.1
    End_Time:      200.0
    Randomseed:    -1
    Nevents:       1

Output:
    Output_Interval:  5.0
    Particles:
        Format:          ["Oscar2013"]

Collision_Term:
    Included_2to2:       ["All"] # Options are ["All", "Elastic", "NN_to_NR",
                                    # "NN_to_DR", "KN_to_KN", "KN_to_KDelta",
                                    # "Strangeness_exchange"]
                                    # Empty brackets results in no 2 to 2 reactions

Modi:
    Collider:
        Projectile:
            Particles: {2212: 79, 2112: 118} #Gold197
        Target:
            Particles: {2212: 79, 2112: 118} #Gold197

        E_Kin: 1.23
        Fermi_Motion: "frozen"
