Logging:
    default: INFO

General:
    Modus:         List
    Time_Step_Mode: None
    Delta_Time:    0.1
    End_Time:      50.0
    Randomseed:    -1
    Nevents:       10

Output:
    Particles:
        Format:          ["Oscar2013"]

Modi:
    List:
        File_Directory: "../input/"
        File_Prefix: "example_list"
        Shift_Id: 0
