Logging:
  default: INFO

General:
    Modus:         Collider
    Time_Step_Mode: Fixed
    Delta_Time:    0.1
    End_Time:      100.0
    Randomseed:    -1
    Testparticles: 20
    Nevents:       10
    Use_Grid: True

Output:
    Output_Interval:  1.0
    Particles:
        Format:          ["Oscar2013", "Binary"]
        Extended:        True
    Collisions:
        Format:          ["Oscar2013", "Binary"]
        Extended:        True
        Print_Start_End: True


Modi:
    Collider:
        Projectile:
            Particles: {2212: 79, 2112: 118} #Gold197
        Target:
            Particles: {2212: 79, 2112: 118} #Gold197

        E_Kin: 1.23
        Fermi_Motion: "frozen"
        Collisions_Within_Nucleus: False
