language: cpp

sudo: required

branches:
  only:
  - master
  - devel

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
  - os: osx
    compiler: gcc

addons:
  apt:
    packages:
    - libboost-all-dev
  homebrew:
    packages:
    - boost

before_install:
  - export SMASH_ROOT=$(pwd)
  # clang-format
  - if [ $TRAVIS_OS_NAME = osx ]; then curl -# -o clang6_0_0.tar.xz http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-apple-darwin.tar.xz;
    else  curl -# -o clang6_0_0.tar.xz http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz; fi &&
    mkdir clang6_0_0 && tar -xf clang6_0_0.tar.xz -C clang6_0_0 --strip-components=1 &&
    export PATH=$SMASH_ROOT/clang6_0_0/bin/:$PATH
  # gsl
  - wget http://ftpmirror.gnu.org/gsl/gsl-1.15.tar.gz &&
    tar -zxf gsl-1.15.tar.gz &&
    export GSL=$(pwd)/gsl-1.15 &&
    cd $GSL &&
    ./configure --prefix $GSL &&
    make -j2 --silent &&
    make install --silent &&
    cd $SMASH_ROOT
  # eigen
  - wget http://bitbucket.org/eigen/eigen/get/3.3.5.tar.gz &&
    tar -xf 3.3.5.tar.gz -C $HOME
  # cpplint
  - pip install --user cpplint

install:
  - cd $SMASH_ROOT
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/eigen-eigen-b3f3d4950030/ -DGSL_ROOT_DIR=$GSL ..
  - make -j2

script:
  - ctest -j2
  - cd ../bin && ./clang-format-helper.sh -t
