Logging:
  default: INFO
  #Legacy: ALL
  #Main: ALL
  #Experiment: ALL
  #Box: ALL
  #Collider: ALL
  #Nucleus: ALL
  #Sphere: ALL
  #ParticleType: ALL
  #Action: ALL
  #FindScatter: ALL

General:
    # Modus decision
    MODUS:         Nucleus

    # temporal grid spacing
    DELTA_TIME:    0.01

    # end time of simulation
    END_TIME:      1.0

    # output formats
    OUTPUT:
        OSCAR_COLLISIONS:
            Enable:             True
            2013_format:        True
            Print_start_end:    False
        OSCAR_PARTICLELIST:
            Enable:             True
            2013_format:        True
            Only_final:         True
        VTK:
            Enable:             False
        ROOT:
            Enable:             True
            write_collisions:   True
            write_particles:    True
            autosave_frequency: 1000
        Binary_collisions:
            Enable:             True
            print_start_end:    True
        Binary_particles:
            Enable:             True
            only_final:         False

    # how much time before recording measurables
    OUTPUT_INTERVAL:  1.0

    # initial random seed (auto-generated if negative)
    RANDOMSEED:    1

    # elastic cross section
    SIGMA:         10.0

    # number of test particle
    TESTPARTICLES: 1

    # number of events
    NEVENTS:       1

Modi:
    Box:
        # Cube size
        LENGTH: 10.0

        # initialization temperature
        TEMPERATURE: 0.2

        # initial condition
        #
        # 1:  random position box + thermal momenta
        # 2:  random position box + peaked momenta
        #
        INITIAL_CONDITION: 1

        # start time of simulation
        START_TIME:    0.0

        INIT_MULTIPLICITIES:
            221:    100
            111:    200
            2112:   20

    Sphere:
        # Sphere size
        RADIUS: 5.0
        # Current temperature
        SPHERETEMPERATURE: 0.2
        # start time of simulation
        START_TIME: 0.0
        # Number of particles in Sphere
        INIT_MULTIPLICITIES:
            221:    100
            111:    200
            2112:   20


    Collider:
        # Projectile particle
        PROJECTILE: 211

        # Target particle
        TARGET: -211

        # center-of-mass energy in GeV
        SQRTS: 1.0

    Nucleus:
        # Definitions for the projectile:
        # Deuteron
        Projectile:
            PARTICLES: {2212: 1, 2112: 1}
            # very hard Woods-Saxon distribution.
            DIFFUSIVENESS: .001
            AUTOMATIC: false
            DEFORMED: false
        # Definitions for the target:
        # Lead
        Target:
            PARTICLES: {2212: 82, 2112: 126}
            AUTOMATIC: true
            DEFORMED: false

        # Collision energy (E_LAB, P_LAB, SQRTSNN).
        SQRTSNN: 2
        # The representative particles (two PDG IDs) determining the
        # subsystem "NN" in sqrt(s_NN). Let's try neutron-neutron.
        SQRTS_REPS: [2112, 2112]
        # The reference frame in which to do the calculation.
        # (1 = center of velocity, 2 = center of mass, 3 = fixed target)
        CALCULATION_FRAME: 1
